/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/ledger.ts
 * Command: astryx theme build src/theme/ledger.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const ledgerTheme: DefinedTheme;
