/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/ledger.ts
 * Command: astryx theme build src/theme/ledger.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * ledger theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { ledgerTheme } from './ledger';
 *   import './ledger.css';
 */
export const ledgerTheme = {
  name: 'ledger',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.1875rem",
    "--font-size-3xs": "0.25rem",
    "--font-size-2xs": "0.3125rem",
    "--font-size-xs": "0.5rem",
    "--font-size-sm": "0.6875rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.3125rem",
    "--font-size-xl": "1.8125rem",
    "--font-size-2xl": "2.5625rem",
    "--font-size-3xl": "3.625rem",
    "--font-size-4xl": "5.0625rem",
    "--font-size-5xl": "7.0625rem",
    "--text-heading-1-size": "41px",
    "--text-heading-1-weight": "800",
    "--text-heading-1-leading": "1.0244",
    "--text-heading-2-size": "29px",
    "--text-heading-2-weight": "700",
    "--text-heading-2-leading": "1.1034",
    "--text-heading-3-size": "21px",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.3333",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.4545",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.5",
    "--text-body-size": "15px",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4667",
    "--text-large-size": "21px",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4286",
    "--text-label-size": "11px",
    "--text-label-weight": "var(--font-weight-bold)",
    "--text-label-leading": "1.4545",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "13px",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.3846",
    "--text-display-1-size": "57px",
    "--text-display-1-weight": "900",
    "--text-display-1-leading": "0.9474",
    "--text-display-2-size": "41px",
    "--text-display-2-weight": "800",
    "--text-display-2-leading": "1.0244",
    "--text-display-3-size": "29px",
    "--text-display-3-weight": "700",
    "--text-display-3-leading": "1.1034",
    "--duration-fast-min": "90ms",
    "--duration-fast": "120ms",
    "--duration-fast-max": "160ms",
    "--duration-medium-min": "180ms",
    "--duration-medium": "240ms",
    "--duration-medium-max": "320ms",
    "--duration-slow-min": "450ms",
    "--duration-slow": "600ms",
    "--duration-slow-max": "800ms",
    "--font-family-body": "\"IBM Plex Sans\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
    "--font-family-heading": "Archivo, \"Archivo Black\", Impact, \"Arial Black\", sans-serif",
    "--font-family-code": "\"IBM Plex Mono\", ui-monospace, SFMono-Regular, Menlo, monospace",
    "--color-background-body": "light-dark(#eef3f1, #0b1211)",
    "--color-background-surface": "light-dark(#ffffff, #142120)",
    "--color-background-card": "light-dark(#ffffff, #142120)",
    "--color-background-popover": "light-dark(#ffffff, #142120)",
    "--color-background-muted": "light-dark(#e2ebe8, #1c2b29)",
    "--color-background-inverted": "light-dark(#0f1a19, #eef3f1)",
    "--color-text-primary": "light-dark(#0f1a19, #edf4f2)",
    "--color-text-secondary": "light-dark(#3f5250, #b9cac6)",
    "--color-text-disabled": "light-dark(#526663, #8fa3a0)",
    "--color-text-accent": "light-dark(#066e63, #2fd2be)",
    "--color-icon-primary": "light-dark(#0f1a19, #edf4f2)",
    "--color-icon-secondary": "light-dark(#3f5250, #b9cac6)",
    "--color-icon-disabled": "light-dark(#526663, #8fa3a0)",
    "--color-icon-accent": "light-dark(#066e63, #2fd2be)",
    "--color-on-dark": "#eef3f1",
    "--color-on-light": "#0f1a19",
    "--color-accent": "light-dark(#066a60, #1fc2b0)",
    "--color-on-accent": "light-dark(#ffffff, #04211d)",
    "--color-accent-muted": "light-dark(#cdeee9, #103a35)",
    "--focus-outline-color": "light-dark(#b23fa6, #e07bd3)",
    "--focus-outline-width": "2px",
    "--focus-outline-offset": "2px",
    "--color-border": "light-dark(#c6d4d0, #26403d)",
    "--color-border-emphasized": "light-dark(#6a817e, #6f8683)",
    "--color-track": "light-dark(#e2ebe8, #1c2b29)",
    "--color-skeleton": "light-dark(#c6d4d0, #26403d)",
    "--color-success": "light-dark(#176f47, #5fd39a)",
    "--color-success-muted": "light-dark(#176f4726, #5fd39a33)",
    "--color-on-success": "light-dark(#ffffff, #04211d)",
    "--color-warning": "light-dark(#8c5a00, #e6b34a)",
    "--color-warning-muted": "light-dark(#8c5a0026, #e6b34a33)",
    "--color-on-warning": "light-dark(#0f1a19, #0f1a19)",
    "--color-error": "light-dark(#b8322a, #ff8a80)",
    "--color-error-muted": "light-dark(#b8322a26, #ff8a8033)",
    "--color-on-error": "light-dark(#ffffff, #04211d)",
    "--shadow-low": "light-dark(8px 8px 0 #0f1a19, 8px 8px 0 #1fc2b0)",
    "--shadow-med": "light-dark(12px 12px 0 #0f1a19, 12px 12px 0 #1fc2b0)",
    "--shadow-high": "light-dark(0 12px 32px rgba(15, 26, 25, 0.24), 0 12px 32px rgba(0, 0, 0, 0.7))",
    "--color-shadow": "light-dark(rgba(15, 26, 25, 0.24), rgba(0, 0, 0, 0.7))",
    "--radius-inner": "2px",
    "--radius-element": "0px",
    "--radius-container": "0px",
    "--radius-page": "0px",
    "--radius-chat": "0px"
  },
  localTokens: {
    "--ledger-page-top": "light-dark(#f3f7f6, #101b1a)",
    "--ledger-page-bottom": "light-dark(#e1eae7, #070d0c)",
    "--ledger-page-glow": "light-dark(#0a9d8d38, #1fc2b042)",
    "--ledger-page-glow-2": "light-dark(#b23fa62b, #e07bd336)",
    "--ledger-card-top": "light-dark(#ffffff, #182827)",
    "--ledger-card-bottom": "light-dark(#f0f6f4, #0f1b1a)",
    "--ledger-card-edge": "light-dark(#0f1a19, #1fc2b0)",
    "--ledger-chevron-ink": "light-dark(#0f1a19, #edf4f2)",
    "--ledger-counter": "light-dark(#b23fa6, #e07bd3)",
    "--ledger-counter-glow": "light-dark(#b23fa64d, #e07bd35c)",
    "--ledger-hatch": "light-dark(#ffffff73, #ffffff40)",
    "--ledger-accent-deep": "light-dark(#04574e, #9df0e4)",
    "--ledger-accent-glow": "light-dark(#0a9d8d66, #1fc2b080)",
    "--ledger-series-1": "light-dark(#0a9d8d, #009283)",
    "--ledger-series-1-deep": "light-dark(#036e63, #007d70)",
    "--ledger-series-2": "light-dark(#b23fa6, #c465b8)",
    "--ledger-series-2-deep": "light-dark(#7f2a77, #9a4691)",
    "--ledger-series-3": "light-dark(#7a8f10, #7f9a22)",
    "--ledger-series-3-deep": "light-dark(#55650a, #5b6f16)",
    "--ledger-series-4": "light-dark(#4a4fc4, #7f82d6)",
    "--ledger-series-muted": "light-dark(#a9b8b4, #3a4f4c)",
    "--ledger-div-neg": "light-dark(#b23fa6, #c465b8)",
    "--ledger-div-mid": "light-dark(#b8c5c1, #3a4f4c)",
    "--ledger-div-pos": "light-dark(#0a9d8d, #009283)",
    "--ledger-shadow-glow": "light-dark(0 0 0 2px #0a9d8d55, 0 8px 28px -2px #0a9d8d66, 0 0 0 2px #1fc2b066, 0 8px 32px -2px #1fc2b080)",
    "--ledger-notch-sm": "8px",
    "--ledger-notch-lg": "16px",
    "--ledger-notch-xl": "32px",
    "--ledger-offset-3d": "8px",
    "--ledger-offset-3d-hover": "12px",
    "--ledger-chevron-pitch": "16px",
    "--ledger-chevron-angle": "45deg",
    "--ledger-bar-thickness": "24px",
    "--ledger-measure": "64ch"
  },
  __localTokenOwners: {
    "--ledger-page-top": "ledger",
    "--ledger-page-bottom": "ledger",
    "--ledger-page-glow": "ledger",
    "--ledger-page-glow-2": "ledger",
    "--ledger-card-top": "ledger",
    "--ledger-card-bottom": "ledger",
    "--ledger-card-edge": "ledger",
    "--ledger-chevron-ink": "ledger",
    "--ledger-counter": "ledger",
    "--ledger-counter-glow": "ledger",
    "--ledger-hatch": "ledger",
    "--ledger-accent-deep": "ledger",
    "--ledger-accent-glow": "ledger",
    "--ledger-series-1": "ledger",
    "--ledger-series-1-deep": "ledger",
    "--ledger-series-2": "ledger",
    "--ledger-series-2-deep": "ledger",
    "--ledger-series-3": "ledger",
    "--ledger-series-3-deep": "ledger",
    "--ledger-series-4": "ledger",
    "--ledger-series-muted": "ledger",
    "--ledger-div-neg": "ledger",
    "--ledger-div-mid": "ledger",
    "--ledger-div-pos": "ledger",
    "--ledger-shadow-glow": "ledger",
    "--ledger-notch-sm": "ledger",
    "--ledger-notch-lg": "ledger",
    "--ledger-notch-xl": "ledger",
    "--ledger-offset-3d": "ledger",
    "--ledger-offset-3d-hover": "ledger",
    "--ledger-chevron-pitch": "ledger",
    "--ledger-chevron-angle": "ledger",
    "--ledger-bar-thickness": "ledger",
    "--ledger-measure": "ledger"
  },
  __localTokenLineage: ["ledger"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)",
        "fontStretch": "112%",
        "letterSpacing": "-0.025em"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)",
        "fontStretch": "100%",
        "letterSpacing": "-0.02em"
      },
      "level:3": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--font-weight-semibold)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)",
        "textTransform": "uppercase",
        "fontStretch": "125%",
        "letterSpacing": "-0.03em"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)",
        "fontStretch": "112%",
        "letterSpacing": "-0.025em"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)",
        "fontStretch": "100%",
        "letterSpacing": "-0.02em"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "type:eyebrow": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "11px",
        "lineHeight": "16px",
        "fontWeight": "700",
        "letterSpacing": "0.14em",
        "textTransform": "uppercase"
      },
      "type:figure-xl": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "80px",
        "lineHeight": "72px",
        "fontWeight": "900",
        "letterSpacing": "-0.04em",
        "fontStretch": "125%",
        "fontVariantNumeric": "tabular-nums"
      },
      "type:figure-md": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "29px",
        "lineHeight": "32px",
        "fontWeight": "800",
        "letterSpacing": "-0.02em",
        "fontStretch": "112%",
        "fontVariantNumeric": "tabular-nums"
      },
      "type:figure-sm": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "13px",
        "lineHeight": "16px",
        "fontWeight": "500",
        "fontVariantNumeric": "tabular-nums"
      }
    },
    "button": {
      "base": {
        "borderRadius": "0px"
      }
    },
    "card": {
      "base": {
        "borderRadius": "0px",
        "backgroundImage": "linear-gradient(180deg, var(--ledger-card-top), var(--ledger-card-bottom))",
        "boxShadow": "none",
        "clipPath": "polygon(0 0, calc(100% - var(--ledger-notch-lg)) 0, 100% var(--ledger-notch-lg), 100% 100%, 0 100%)"
      }
    },
    "clickable-card": {
      "base": {
        "borderRadius": "0px",
        "backgroundImage": "linear-gradient(180deg, var(--ledger-card-top), var(--ledger-card-bottom))",
        "boxShadow": "none",
        "clipPath": "polygon(0 0, calc(100% - var(--ledger-notch-lg)) 0, 100% var(--ledger-notch-lg), 100% 100%, 0 100%)",
        "transition": "transform var(--duration-fast) var(--ease-standard)",
        ":hover": {
          "transform": "translate(-4px, -4px)"
        }
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 15,
        "ratio": 1.4
      },
      "body": {
        "family": "IBM Plex Sans",
        "fallbacks": "system-ui, -apple-system, \"Segoe UI\", sans-serif"
      },
      "heading": {
        "family": "Archivo",
        "fallbacks": "\"Archivo Black\", Impact, \"Arial Black\", sans-serif",
        "weight": "bold"
      },
      "code": {
        "family": "IBM Plex Mono",
        "fallbacks": "ui-monospace, SFMono-Regular, Menlo, monospace"
      }
    },
    "motion": {
      "fast": 120,
      "medium": 240,
      "slow": 600,
      "ratio": 0.75
    }
  },

};
