/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/ledger.ts
 * Command: astryx theme build src/theme/ledger.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * ledger theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { ledgerTheme } from './ledger';
 *   import './ledger.css';
 */
export const ledgerTheme = {
  name: 'ledger',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "40px",
    "--text-heading-1-weight": "var(--font-weight-medium)",
    "--text-heading-1-leading": "1.1",
    "--text-heading-2-size": "28px",
    "--text-heading-2-weight": "var(--font-weight-medium)",
    "--text-heading-2-leading": "1.2143",
    "--text-heading-3-size": "20px",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-medium)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-medium)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-medium)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "16px",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "18px",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "12px",
    "--text-label-weight": "var(--font-weight-semibold)",
    "--text-label-leading": "1.3333",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "14px",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "64px",
    "--text-display-1-weight": "var(--font-weight-medium)",
    "--text-display-1-leading": "1",
    "--text-display-2-size": "40px",
    "--text-display-2-weight": "var(--font-weight-medium)",
    "--text-display-2-leading": "1.1",
    "--text-display-3-size": "28px",
    "--text-display-3-weight": "var(--font-weight-medium)",
    "--text-display-3-leading": "1.2143",
    "--duration-fast-min": "120ms",
    "--duration-fast": "160ms",
    "--duration-fast-max": "215ms",
    "--duration-medium-min": "180ms",
    "--duration-medium": "240ms",
    "--duration-medium-max": "320ms",
    "--duration-slow-min": "450ms",
    "--duration-slow": "600ms",
    "--duration-slow-max": "800ms",
    "--font-family-body": "\"IBM Plex Sans\", system-ui, -apple-system, \"Segoe UI\", sans-serif",
    "--font-family-heading": "\"Source Serif 4\", Georgia, \"Times New Roman\", serif",
    "--font-family-code": "\"IBM Plex Mono\", ui-monospace, SFMono-Regular, Menlo, monospace",
    "--color-background-body": "light-dark(#f6f4ef, #191816)",
    "--color-background-surface": "light-dark(#ffffff, #221f1c)",
    "--color-background-card": "light-dark(#ffffff, #221f1c)",
    "--color-background-popover": "light-dark(#ffffff, #221f1c)",
    "--color-background-muted": "light-dark(#ebe7df, #2d2a26)",
    "--color-background-inverted": "light-dark(#191815, #f6f4ef)",
    "--color-text-primary": "light-dark(#191815, #f1ede6)",
    "--color-text-secondary": "light-dark(#4d4842, #c6bfb3)",
    "--color-text-disabled": "light-dark(#6b655c, #9a9388)",
    "--color-text-accent": "light-dark(#0e5a57, #7fd0c8)",
    "--color-icon-primary": "light-dark(#191815, #f1ede6)",
    "--color-icon-secondary": "light-dark(#4d4842, #c6bfb3)",
    "--color-icon-disabled": "light-dark(#6b655c, #9a9388)",
    "--color-icon-accent": "light-dark(#0e5a57, #7fd0c8)",
    "--color-on-dark": "#f6f4ef",
    "--color-on-light": "#191815",
    "--color-accent": "light-dark(#0b4a48, #5fb8b0)",
    "--color-on-accent": "light-dark(#ffffff, #0f2725)",
    "--color-accent-muted": "light-dark(#d8e9e6, #1d3a38)",
    "--focus-outline-color": "light-dark(#0e5a57, #7fd0c8)",
    "--focus-outline-width": "2px",
    "--focus-outline-offset": "2px",
    "--color-border": "light-dark(#dcd6cb, #3a3631)",
    "--color-border-emphasized": "light-dark(#8c8477, #8a8378)",
    "--color-track": "light-dark(#ebe7df, #2d2a26)",
    "--color-skeleton": "light-dark(#dcd6cb, #3a3631)",
    "--color-success": "light-dark(#17705c, #5fc9a7)",
    "--color-success-muted": "light-dark(#17705c26, #5fc9a733)",
    "--color-on-success": "light-dark(#ffffff, #0f2725)",
    "--color-warning": "light-dark(#8a5a00, #e0b04a)",
    "--color-warning-muted": "light-dark(#8a5a0026, #e0b04a33)",
    "--color-on-warning": "light-dark(#191815, #191815)",
    "--color-error": "light-dark(#a83226, #f08a7e)",
    "--color-error-muted": "light-dark(#a8322626, #f08a7e33)",
    "--color-on-error": "light-dark(#ffffff, #0f2725)",
    "--shadow-low": "light-dark(0 1px 2px rgba(25, 24, 21, 0.06), 0 16px 40px -16px rgba(25, 24, 21, 0.28), 0 1px 2px rgba(0, 0, 0, 0.4), 0 20px 48px -16px rgba(0, 0, 0, 0.7))",
    "--shadow-med": "light-dark(0 2px 4px rgba(25, 24, 21, 0.06), 0 28px 56px -20px rgba(25, 24, 21, 0.36), 0 2px 4px rgba(0, 0, 0, 0.4), 0 32px 64px -20px rgba(0, 0, 0, 0.8))",
    "--shadow-high": "light-dark(0 8px 28px rgba(25, 24, 21, 0.18), 0 8px 28px rgba(0, 0, 0, 0.6))",
    "--color-shadow": "light-dark(rgba(25, 24, 21, 0.18), rgba(0, 0, 0, 0.6))",
    "--radius-inner": "3px",
    "--radius-element": "6px",
    "--radius-container": "14px",
    "--radius-page": "22px",
    "--radius-chat": "22px"
  },
  localTokens: {
    "--ledger-series-1": "light-dark(#0d8f83, #2ea699)",
    "--ledger-series-2": "light-dark(#c95f14, #d57a3a)",
    "--ledger-series-3": "light-dark(#6a4fbf, #9583d6)",
    "--ledger-series-4": "light-dark(#a3791a, #b0922e)",
    "--ledger-series-muted": "light-dark(#b9b2a6, #5a554d)",
    "--ledger-div-neg": "light-dark(#c95f14, #d57a3a)",
    "--ledger-div-mid": "light-dark(#c9c3b8, #5a554d)",
    "--ledger-div-pos": "light-dark(#0d8f83, #2ea699)",
    "--ledger-series-1-deep": "light-dark(#0a6d63, #1a8a7e)",
    "--ledger-series-2-deep": "light-dark(#a04a0e, #b85f27)",
    "--ledger-series-3-deep": "light-dark(#513a9e, #7a67c4)",
    "--ledger-accent-deep": "light-dark(#083f3d, #b2ebe5)",
    "--ledger-accent-glow": "light-dark(#0d8f8352, #2ea69966)",
    "--ledger-page-top": "light-dark(#faf8f3, #1d1c19)",
    "--ledger-page-bottom": "light-dark(#ebe5d9, #121110)",
    "--ledger-page-glow": "light-dark(#0e5a5729, #7fd0c824)",
    "--ledger-card-top": "light-dark(#ffffff, #2a2723)",
    "--ledger-card-bottom": "light-dark(#f7f3ec, #1e1c19)",
    "--ledger-card-highlight": "light-dark(#ffffffcc, #ffffff14)",
    "--ledger-shadow-glow": "light-dark(0 0 0 1px #0d8f8333, 0 8px 28px -4px #0d8f8352, 0 0 0 1px #2ea69944, 0 8px 32px -4px #2ea69966)",
    "--ledger-bar-thickness": "24px",
    "--ledger-measure": "68ch"
  },
  __localTokenOwners: {
    "--ledger-series-1": "ledger",
    "--ledger-series-2": "ledger",
    "--ledger-series-3": "ledger",
    "--ledger-series-4": "ledger",
    "--ledger-series-muted": "ledger",
    "--ledger-div-neg": "ledger",
    "--ledger-div-mid": "ledger",
    "--ledger-div-pos": "ledger",
    "--ledger-series-1-deep": "ledger",
    "--ledger-series-2-deep": "ledger",
    "--ledger-series-3-deep": "ledger",
    "--ledger-accent-deep": "ledger",
    "--ledger-accent-glow": "ledger",
    "--ledger-page-top": "ledger",
    "--ledger-page-bottom": "ledger",
    "--ledger-page-glow": "ledger",
    "--ledger-card-top": "ledger",
    "--ledger-card-bottom": "ledger",
    "--ledger-card-highlight": "ledger",
    "--ledger-shadow-glow": "ledger",
    "--ledger-bar-thickness": "ledger",
    "--ledger-measure": "ledger"
  },
  __localTokenLineage: ["ledger"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--font-weight-semibold)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "type:eyebrow": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "12px",
        "lineHeight": "16px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.08em",
        "textTransform": "uppercase"
      },
      "type:figure-xl": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "72px",
        "lineHeight": "72px",
        "fontWeight": "var(--font-weight-medium)",
        "letterSpacing": "-0.02em",
        "fontVariantNumeric": "tabular-nums"
      },
      "type:figure-md": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "24px",
        "lineHeight": "28px",
        "fontWeight": "var(--font-weight-medium)",
        "fontVariantNumeric": "tabular-nums"
      },
      "type:figure-sm": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "13px",
        "lineHeight": "16px",
        "fontWeight": "var(--font-weight-medium)",
        "fontVariantNumeric": "tabular-nums"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-container)",
        "backgroundImage": "linear-gradient(180deg, var(--ledger-card-top), var(--ledger-card-bottom))",
        "boxShadow": "inset 0 1px 0 var(--ledger-card-highlight), var(--shadow-low)"
      }
    },
    "clickable-card": {
      "base": {
        "borderRadius": "var(--radius-container)",
        "backgroundImage": "linear-gradient(180deg, var(--ledger-card-top), var(--ledger-card-bottom))",
        "boxShadow": "inset 0 1px 0 var(--ledger-card-highlight), var(--shadow-low)",
        "transition": "box-shadow var(--duration-fast) var(--ease-standard), transform var(--duration-fast) var(--ease-standard)",
        ":hover": {
          "boxShadow": "inset 0 1px 0 var(--ledger-card-highlight), var(--shadow-med)",
          "transform": "translateY(-2px)"
        }
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "IBM Plex Sans",
        "fallbacks": "system-ui, -apple-system, \"Segoe UI\", sans-serif"
      },
      "heading": {
        "family": "Source Serif 4",
        "fallbacks": "Georgia, \"Times New Roman\", serif",
        "weight": "medium"
      },
      "code": {
        "family": "IBM Plex Mono",
        "fallbacks": "ui-monospace, SFMono-Regular, Menlo, monospace"
      }
    },
    "motion": {
      "fast": 160,
      "medium": 240,
      "slow": 600,
      "ratio": 0.75
    }
  },

};
